config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
 }

 resources :positions do
  post 'apply', on: :member
end

  


  # resources :users do
    # get 'new_user_registration', on: :collection
  # end

 
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/position.rb
class Position < ApplicationRecord
    has_and_belongs_to_many :users
    # has_and_belongs_to_many :positions_users, class_name: 'User', join_table: :positions_users
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :authorize_admin, only: [:create, :update, :edit, :destroy]
  before_action :set_position, only: [ :show, :edit, :update, :destroy ]

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end
  
  # GET /positions/1 or /positions/1.json
  def show    
    @position = Position.find(params[:id])
    @applicants = @position.users
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to position_url(@position), notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to position_url(@position), notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def apply
    @position = Position.find(params[:id])
    current_user.positions << @position
  
    redirect_to @position, notice: 'Te has postulado correctamente a esta oferta laboral.'
  end
  

  def apply_show   
      @position = Position.find(params[:id])
      @applicants = @position.users  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:title, :description, :responsibilities, :requirements, :salary)
    end

    def authorize_admin
      unless current_user.admin?
        redirect_to home_index_path, notice: "No estás autorizado para hacer esta acción"
      end
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_apply_show.html.erb
                              <ul>
                                <% @applicants.each do |applicant| %>
                                  <li><%= applicant.username %></li>
                                  <!-- Mostrar otras propiedades del usuario según tus necesidades -->
                                <% end %>
                              </ul>

app/views/positions/_form.html.erb
<%= form_with(model: position) do |form| %>
  <% if position.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :responsibilities, style: "display: block" %>
    <%= form.text_area :responsibilities, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :requirements, style: "display: block" %>
    <%= form.text_area :requirements, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/_position.html.erb
<div class="container d-inline justify-content-center align-items-center">   
    <div id="<%= dom_id position %>">  
      <div class="card w-75 mt-5">        
         <div class="card-body">          
            <h5 class="card-title"><strong>Cargo:</strong>
            <%= position.title %></h5>       
      
            <p class="card-text text-start"> <p><strong>Descripción:</strong>
               <%= position.description %></p>
            <p class="card-text text-start"> <p><strong>Responsabilidades:</strong>
               <%= position.responsibilities %></p>  
            <p class="card-text text-start"> <p><strong>Requisitos:</strong>
               <%= position.requirements %></p> 
            <p class="card-text text-start"> <p><strong>Sueldo:</strong>
               <%= position.salary %></p>  
                <p><%= link_to "Show this position", position, class: "btn btn-primary"%></p>
         </div>          
      </div>
    </div>  
</div>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render "form", position: @position %>

<br>

<div>
  <%= link_to "Show this position", @position %> |
  <%= link_to "Back to positions", positions_path %>
</div>

app/views/positions/index.html.erb
<div class= "container">  
    <p style="color: green"><%= notice %></p>
    <div id="positions" class="row row-cols-1 row-cols-md-3 g-4">
      <% if user_signed_in?%>
        <h1>Ofertas laborales</h1>    
          <% @positions.each do |position| %>
            <div class="col">
              <%= render position %>
             </div>
           
          <% end %>
        </div>
          <% if current_user.admin? %>
            <%= link_to "New position", new_position_path %>            
          <% end %>
      <%else%>
        
      <% end %>   
    </div> 
</div> 

app/views/positions/new.html.erb
<div class="container">
  <div class="row">
      <div class="col">
      </div>
      <div class="col">
        <h1>New position</h1>
        <%= render "form", position: @position %>
       </div>
      <div class="col">
      </div>          
      <div class="container mt-5 text-center">
          <%= link_to "Back to positions", positions_path %>
      </div>
  </div>
</div>

app/views/positions/show.html.erb
 <div class="container d-block justify-content-center align-items-center">   
    <p style="color: green"><%= notice %></p>

  <div class="row">
    <div class="col-3">
    </div>
    <div class="col">
      <%= render @position %>   

        <nav class="nav pt-3 pb-3"> 
                <% if user_signed_in? %>  
                  <div class="d-flex">           
                    <%= button_to "Postular", apply_position_path(@position), method: :post, class: "btn btn btn-secondary text-white mt-2 ms-3" %>  
                    
              
                  </div>
                <% end %>
                <% if current_user.admin?%>          
                  <div class="d-flex">
                    <%= button_to "Editar", edit_position_path(@position), method: :get, class: "btn btn btn-secondary mt-2 ms-3" %>
                    <%= button_to "Eliminar", position_path(@position), method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn btn-secondary  mt-2 ms-3 me-5" %>      
                    <%= button_to "Volver a ofertas", positions_path, method: :get, class: "btn btn btn-secondary  mt-2 ms-3 me-5"%>
                  </div>  
                  <div class="container mt-5">
                    <% @applicants.each do |applicant| %>
                        <div class="card text-bg-tertiary mb-3 mt-5" style="max-width: 18rem;">
                          <div class="card-header">Postulaciones</div>
                            <div class="card-body">        
                              <h5 class="card-title"></h5>
                               <p class="card-text"></p>
                                      <ul>
                                      
                                          <li><strong>Username: </strong><%= applicant.username %></li>
                                          <li><strong>Cargo actual: </strong><%= applicant.current_role %></li>
                                          <li><strong>Habilidades: </strong><%= applicant.skill %></li>
                                          <li><strong>Experiencia: </strong><%= applicant.experience %></li>
                                          
                                      
                                      </ul>
                            </div>
                          </div>
                        </div>
                    <% end %>
                  </div>  
                <% end %>   
        </nav>
              
    </div>
    <div class="col-3">          
    </div> 
</div>